### ISSUE TITLE
PDT Time link incorrect?

### ISSUE THREAD

**Issue by mikemahoney218** [r-devel/c-book-club#3]
Hi all,

I noticed that the PDT time link goes to https://everytimezone.com/s/c2b9b79d , which I believe is for 2pm PDT. Should that be https://everytimezone.com/s/5ec9c2d4 , which is 7pm PDT, or is the time zone label incorrect?

Thanks!

**Comment by hturner** [comment]
Thanks for filing this issue, commit aca18bc7c252c2d7114e90b4c982f2a1c7129c24 fixed this.
